title: Ronnie Beltran
email:
description: > # this means to ignore newlines until "baseurl:"
  Web development using Python, HTML, CSS and JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ronbeltran.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ronbeltran
github_username:  ronbeltran

# Build settings
permalink: /:year/:month/:title.html
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: UA-47323896-6
